### PR TITLE
Fixes to run interactive scenarios

### PR DESCRIPTION
**Pull request by rzilleruelo**
* Modify how the color lists are built. Removed alpha dimension of the
  color. Given its value is set by the environment generating a double
  passing the alpha parameter

### CODE REVIEW

**Comment by agakshat** [comment]
I'm not sure if the correction to prevent a crash when environment returns None reward is correct, because currently the `_get_reward` function does not return _anything_ at all. It is this: 
`def _get_reward(self, agent):`
    ` if self.reward_callback is None:`
    `return 0.0`
    `self.reward_callback(agent, self.world)`.

**Comment by rzilleruelo** [comment]
```bash
$ bin/interactive.py --scenario simple_adversary.py
agent 1 to agent 0: _   agent 2 to agent 0: _   agent 0 to agent 1: _   agent 2 to agent 1: _   agent 0 to agent 2: _   agent 1 to agent 2: _
Traceback (most recent call last):
  File "bin/interactive.py", line 34, in <module>
    obs_n, reward_n, done_n, _ = env.step(act_n)
  File "/Users/zeta/zeta/openai/multiagent-particle-envs/.python/openai-multiagent-particle-envs/lib/python3.6/site-packages/gym/core.py", line 96, in step
    return self._step(action)
  File "/Users/zeta/zeta/openai/multiagent-particle-envs/bin/../multiagent/environment.py", line 98, in _step
    reward = np.sum(reward_n)
  File "/Users/zeta/zeta/openai/multiagent-particle-envs/.python/openai-multiagent-particle-envs/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1834, in sum
    out=out, **kwargs)
  File "/Users/zeta/zeta/openai/multiagent-particle-envs/.python/openai-multiagent-particle-envs/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
agent 1 to agent 0: _   agent 2 to agent 0: _   agent 0 to agent 1: _   agent 2 to agent 1: _   agent 0 to agent 2: _   agent 1 to agent 2: _
```

**Comment by rzilleruelo** [comment]
@agakshat, ok I checked your PR https://github.com/openai/multiagent-particle-envs/pull/7 and tried locally. Your fix the right reason of the issue regarding the None rewards 👍 .

The only issue still remains, is the 4 dimension color, which conflicts with the code that set the alpha twice https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py#L231.

**Comment by mordatch** [comment]
You're right, it looks like reward was not returning anything - thanks for pointing this out!

**Pull request merged**
